### ISSUE TITLE
[Feature]: add ability to assume multiple roles during runtime

### ISSUE THREAD

**Issue by emylincon** [emylincon/aws_quota_exporter#76]
**Describe feature to implement**
* Add the ability to assume multiple roles during runtime
* This will change the `config.yml` file to the following
```yaml
jobs:
  - serviceCode: lambda
    regions:
      - us-west-1
      - us-east-1
    role: arn:aws:iam::ACCOUNT-ID:role/rolename
  - serviceCode: cloudformation
    regions:
      - us-west-1
      - us-east-1
    role: arn:aws:iam::ACCOUNT-ID:role/rolename
```
* Additionally the Prometheus labels should change to the following 
```golang
metric := &PrometheusMetric{
	Name:   metricName,
	Value:  *v.Value,
	Labels: map[string]string{"adjustable": strconv.FormatBool(v.Adjustable), "global_quota": strconv.FormatBool(v.GlobalQuota), "unit": *v.Unit, "region": region, "account": account},
	Desc:   *v.QuotaName,
	}
```
